RUNKEEPER_CLIENT_ID="RNKPR_ID"
RUNKEEPER_CLIENT_SECRET="RNKPR_SCRT"

DROPBOX_FULL_APP_KEY = "DRPBX_FULL_KEY"
DROPBOX_FULL_APP_SECRET = "DRPBX_FULL_SCRT"

DROPBOX_APP_KEY = "DRPBX_APP_KEY"
DROPBOX_APP_SECRET = "DRPBX_APP_SCRT"

STRAVA_CLIENT_SECRET = "STRVA_SCRT"
STRAVA_CLIENT_ID = "STRVA_ID"

RWGPS_APIKEY = "GWGPS_KEY"

SPORTTRACKS_CLIENT_SECRET = "SPRTRKS_SCRT"
